from typing import Optional, Dict, Any, List
from datetime import datetime
import json
import uuid
from app.core.logger import get_logger
from app.repositories.user_identity_repository import UserIdentityRepository
from app.utils.country_code_converter import convert_to_alpha3
from app.utils.date_parser import parse_date_to_mariadb


class UserIdentitiesService:
    """Service for managing persistent user identity data using UUID-based indexing.

    Identity lifecycle:
    1. Selfie step: user_identity_index row created with UUID (via create_empty_identity)
    2. Passport step: existing row updated with passport data (via update_passport_data)
    3. Bank statement step: existing row updated with bank data (via update_bank_statement_data)
    """

    def __init__(self):
        self.logger = get_logger()
        self.user_identity_repo = UserIdentityRepository()

    def create_empty_identity(self) -> Optional[str]:
        """Create an empty user identity record at selfie step.

        UUID is auto-generated by database. Passport data will be added later.

        Returns:
            user_identity_id (UUID) if successful, None otherwise
        """
        try:
            user_identity_id = self.user_identity_repo.create_empty_identity()
            if user_identity_id:
                self.logger.info(f"Created empty user identity: {user_identity_id}")
            else:
                self.logger.error("Failed to create empty user identity")
            return user_identity_id
        except Exception as e:
            self.logger.error(f"Failed to create empty identity: {e}")
            return None

    def get_identity_by_id(self, user_identity_id: str) -> Optional[Dict[str, Any]]:
        """Get user identity by UUID"""
        try:
            result = self.user_identity_repo.get_user_by_id(user_identity_id)
            if result:
                self.logger.info(f"Found user identity: {user_identity_id}")
            else:
                self.logger.info(f"No user identity found for id: {user_identity_id}")
            return result
        except Exception as e:
            self.logger.error(f"Failed to get identity by id: {e}")
            return None

    def update_passport_data(self, user_identity_id: str, passport_data: Dict[str, Any],
                           user_public_key: str,
                           face_embedding: Optional[List[float]] = None,
                           face_match_score: Optional[float] = None) -> bool:
        """Update existing user identity with passport data.

        Called at passport step to update the row created at selfie step.

        Args:
            user_identity_id: UUID of the user identity (from selfie step)
            passport_data: Passport data dict containing extracted_data
            user_public_key: User's public key for ECIES encryption
            face_embedding: Not used (face embedding stored in face_biometrics table)
            face_match_score: Not used (logged but not stored)

        Returns:
            True if update successful
        """
        try:
            self.logger.info(f"🔍 UPDATING PASSPORT DATA for user_identity: {user_identity_id[:16]}...")
            self.logger.info(f"🔍 PASSPORT DATA TYPE: {type(passport_data)}")
            self.logger.info(f"🔍 PASSPORT DATA KEYS: {list(passport_data.keys()) if isinstance(passport_data, dict) else 'NOT A DICT'}")

            # Extract passport details
            extracted_data = self._extract_passport_details(passport_data)

            passport_country = extracted_data.get('passport_country')
            passport_number = extracted_data.get('passport_number')

            if not passport_country or not passport_number:
                self.logger.error("Missing passport country or number for update")
                return False

            # Note: passport_hash removed - uniqueness enforced by face biometrics trigger.
            # Same passport can be re-encrypted for different device keys (multi-device support).

            # Update existing identity row with passport data
            success = self.user_identity_repo.update_with_passport_data(
                user_identity_id=user_identity_id,
                passport_country=passport_country,
                passport_number=passport_number,
                user_public_key=user_public_key,
                full_name=extracted_data.get('full_name'),
                date_of_birth=extracted_data.get('date_of_birth'),
                gender=extracted_data.get('gender'),
                passport_expiry_date=extracted_data.get('passport_expiry_date')
            )

            if success:
                self.logger.info(f"✅ Updated passport data for user_identity {user_identity_id}")
            else:
                self.logger.error(f"Failed to update passport data for user_identity {user_identity_id}")

            return success

        except ValueError:
            # Re-raise duplicate passport error
            raise
        except Exception as e:
            self.logger.error(f"Failed to update passport data: {e}")
            return False

    def update_bank_statement_data(self, user_identity_id: str, bank_data: Dict[str, Any]) -> bool:
        """Update user identity with bank statement data (address and statement date).

        DEPRECATED: All document data is now stored in document_submissions.extracted_data_encrypted.
        This method is kept for backward compatibility and always returns True.

        Args:
            user_identity_id: UUID of the user identity
            bank_data: Bank statement data dict containing extracted_data

        Returns:
            True (no-op for backward compatibility)
        """
        self.logger.info(
            f"update_bank_statement_data called for {user_identity_id} - "
            f"no-op: data already stored in document_submissions.extracted_data_encrypted"
        )
        return True

    def get_identity_progress(self, user_identity_id: str) -> Dict[str, Any]:
        """Get progress information for user identity"""
        identity = self.get_identity_by_id(user_identity_id)
        if not identity:
            return {}

        # Determine completed steps based on data presence
        completed_steps = []
        completed_steps.append("selfie")  # Row exists, so selfie was completed

        if identity.get('passport_number'):
            completed_steps.append("passport")

        if identity.get('bank_statement_address') or identity.get('bank_statement_date'):
            completed_steps.append("bank_statement")

        return {
            "identity_id": identity['id'],
            "passport_country": identity.get('passport_country'),
            "passport_number": identity.get('passport_number'),
            "full_name": identity.get('full_name'),
            "date_of_birth": identity.get('date_of_birth'),
            "completed_steps": completed_steps,
            "total_steps": 3,
            "completion_percentage": round((len(completed_steps) / 3) * 100, 2),
            "identity_verified": bool(identity.get('passport_number')),
            "created_at": identity['created_at'].isoformat() if identity.get('created_at') else None,
            "updated_at": identity['updated_at'].isoformat() if identity.get('updated_at') else None
        }

    def _extract_passport_details(self, passport_data: Dict[str, Any]) -> Dict[str, Any]:
        """Extract relevant details from passport analysis data"""
        extracted = {}

        try:
            self.logger.info(f"🔍 EXTRACTING PASSPORT DETAILS from: {type(passport_data)}")
            self.logger.info(f"🔍 PASSPORT DATA KEYS: {list(passport_data.keys())}")

            # Handle both formats: single document and list of documents
            documents_to_process = []

            if "documents" in passport_data:
                # Multi-document format
                documents_to_process = passport_data["documents"]
                self.logger.info(f"🔍 MULTI-DOCUMENT FORMAT with {len(documents_to_process)} documents")
            elif passport_data.get("document_type") == "passport":
                # Single document format
                documents_to_process = [passport_data]
                self.logger.info(f"🔍 SINGLE DOCUMENT FORMAT")
            else:
                self.logger.warning(f"🚨 UNKNOWN PASSPORT DATA FORMAT: {passport_data}")

            for doc in documents_to_process:
                self.logger.info(f"🔍 PROCESSING DOCUMENT: {doc.get('document_type')}")
                if doc.get("document_type") == "passport":
                    extracted_data = doc.get("extracted_data", {})
                    self.logger.debug(f"🔍 EXTRACTED DATA KEYS: {list(extracted_data.keys())}")

                    if "full_name" in extracted_data:
                        full_name_data = extracted_data["full_name"]
                        name_value = full_name_data.get("value") if isinstance(full_name_data, dict) else full_name_data
                        if name_value:
                            extracted['full_name'] = str(name_value)

                    for field_name, field_data in extracted_data.items():
                        if isinstance(field_data, dict) and "value" in field_data:
                            field_value = field_data["value"]

                            if field_name == "date_of_birth" and field_value:
                                # Parse to date object for DATE column
                                extracted['date_of_birth'] = parse_date_to_mariadb(str(field_value))
                            elif field_name == "passport_number" and field_value:
                                extracted['passport_number'] = str(field_value)
                                masked_value = f"{field_value[:4]}****" if len(str(field_value)) > 4 else "****"
                                self.logger.debug(f"✅ Found passport number: {masked_value}")
                            elif field_name == "passport_country" and field_value:
                                # Convert to ISO 3166-1 alpha-3 format
                                country_code = str(field_value)
                                extracted['passport_country'] = convert_to_alpha3(country_code)
                                self.logger.info(f"✅ FOUND PASSPORT COUNTRY: {field_value} -> {extracted['passport_country']}")
                            elif field_name == "passport_expiry_date" and field_value:
                                # Parse to date object for DATE column
                                extracted['passport_expiry_date'] = parse_date_to_mariadb(str(field_value))
                            elif field_name == "date_of_expiry" and field_value:
                                # Alternative field name for passport expiry
                                extracted['passport_expiry_date'] = parse_date_to_mariadb(str(field_value))
                            elif field_name == "sex" and field_value:
                                # Extract gender (M/F) from passport
                                extracted['gender'] = str(field_value)
                                self.logger.info(f"✅ FOUND GENDER: {field_value}")
                        else:
                            self.logger.debug(f"🔍 SKIPPING FIELD {field_name}: {type(field_data)} - {field_data}")

            self.logger.info(f"🔍 FINAL EXTRACTED DATA: {extracted}")

        except Exception as e:
            self.logger.error(f"Error extracting passport details: {str(e)}")

        return extracted

    def _extract_bank_statement_details(self, bank_data: Dict[str, Any]) -> Dict[str, Any]:
        """Extract relevant details from bank statement analysis data"""
        extracted = {}

        try:
            self.logger.info(f"🔍 EXTRACTING BANK STATEMENT DETAILS from: {type(bank_data)}")
            self.logger.info(f"🔍 BANK DATA KEYS: {list(bank_data.keys()) if isinstance(bank_data, dict) else 'NOT A DICT'}")

            if "documents" in bank_data:
                self.logger.info(f"🔍 Found {len(bank_data['documents'])} documents")
                for doc in bank_data["documents"]:
                    self.logger.info(f"🔍 Processing document type: {doc.get('document_type')}")
                    if doc.get("document_type") == "bank_statement":
                        extracted_data = doc.get("extracted_data", {})
                        self.logger.debug(f"🔍 Extracted data fields: {list(extracted_data.keys())}")

                        for field_name, field_data in extracted_data.items():
                            self.logger.info(f"🔍 Processing field: {field_name} = {field_data}")
                            if isinstance(field_data, dict) and "value" in field_data:
                                field_value = field_data["value"]
                                self.logger.info(f"🔍 Field {field_name} value: {field_value}")

                                if "bank_name" in field_name.lower() and field_value:
                                    extracted['bank_name'] = str(field_value)
                                elif "account_number" in field_name.lower() and field_value:
                                    extracted['account_number'] = str(field_value)
                                elif "account_holder" in field_name.lower() or "holder_name" in field_name.lower():
                                    if field_value:
                                        extracted['account_holder_name'] = str(field_value)
                                elif "name" in field_name.lower() and field_value and not extracted.get('account_holder_name'):
                                    # Fallback for name fields
                                    extracted['account_holder_name'] = str(field_value)
                                elif field_name.lower() == "address" and field_value:
                                    extracted['address'] = str(field_value)
                                    self.logger.debug(f"✅ Extracted address: {field_value}")
                                elif field_name.lower() == "statement_date" and field_value:
                                    extracted['statement_date'] = str(field_value)
                                    self.logger.info(f"✅ Extracted statement_date: {field_value}")
                                elif field_name.lower() == "period_ending_date" and field_value and not extracted.get('statement_date'):
                                    # Fallback for statement date
                                    extracted['statement_date'] = str(field_value)
            else:
                self.logger.warning(f"🚨 No 'documents' key found in bank_data")

            self.logger.info(f"🔍 FINAL EXTRACTED BANK STATEMENT DATA: {extracted}")

        except Exception as e:
            self.logger.error(f"Error extracting bank statement details: {str(e)}")

        return extracted