-- ============================================================
-- Migration: Create Bank Prompt Tables
-- Version: v1.13.0
-- Date: 2025-05-25
-- Purpose: Create tables for storing bank-specific GLiNER2 prompts
--          Enables automatic LLM-generated prompts for new banks
-- ============================================================

-- This migration creates the foundation for bank-specific GLiNER2 prompts
-- Prompts are auto-generated by LLM on first encounter with a bank
-- Subsequent extractions use cached prompts for better accuracy

-- ============================================================
-- Table 1: bank_gliner_prompts
-- Stores bank-specific GLiNER2 entity extraction prompts
-- ============================================================

CREATE TABLE IF NOT EXISTS bank_gliner_prompts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bank_id INT NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    entity_type VARCHAR(50) NOT NULL COMMENT 'Field: account_holder_name, account_number, etc.',
    prompt_description TEXT NOT NULL COMMENT 'Natural language description for GLiNER2',
    entity_category VARCHAR(30) DEFAULT 'custom' COMMENT 'PERSON, ORGANIZATION, NUMBER, etc.',
    is_active TINYINT(1) DEFAULT 1,
    threshold FLOAT DEFAULT 0.3 COMMENT 'Confidence threshold',
    examples JSON DEFAULT NULL COMMENT 'Few-shot examples',
    validation_pattern VARCHAR(255) DEFAULT NULL COMMENT 'Regex fallback',
    usage_count INT DEFAULT 0 COMMENT 'Track usage for optimization',
    last_used_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100) DEFAULT 'llm_auto_generated',
    updated_by VARCHAR(100) DEFAULT NULL,
    UNIQUE KEY idx_bank_country_entity (bank_id, country_code, entity_type),
    FOREIGN KEY (bank_id) REFERENCES banks(id) ON DELETE CASCADE,
    INDEX idx_bank_active (bank_id, is_active),
    INDEX idx_lookup (bank_id, country_code, entity_type),
    INDEX idx_entity_type (entity_type),
    INDEX idx_usage (usage_count, last_used_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Bank-specific GLiNER2 prompts (auto-generated by LLM)';

-- ============================================================
-- Table 2: bank_extraction_config
-- Stores extraction configuration for each bank/country combination
-- ============================================================

CREATE TABLE IF NOT EXISTS bank_extraction_config (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bank_id INT NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    default_threshold FLOAT DEFAULT 0.3,
    extraction_order JSON DEFAULT NULL COMMENT 'Priority order for field extraction',
    special_handling JSON DEFAULT NULL COMMENT 'Bank-specific extraction rules',
    is_active TINYINT(1) DEFAULT 1,
    prompt_generation_status VARCHAR(20) DEFAULT 'pending' COMMENT 'pending, in_progress, completed, failed',
    last_generated_at TIMESTAMP NULL,
    samples_processed INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY idx_bank_country (bank_id, country_code),
    FOREIGN KEY (bank_id) REFERENCES banks(id) ON DELETE CASCADE,
    INDEX idx_status (prompt_generation_status),
    INDEX idx_bank_active (bank_id, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Bank extraction configuration and prompt generation status';

-- ============================================================
-- Table 3: prompt_generation_history
-- Audit log for prompt generation attempts
-- ============================================================

CREATE TABLE IF NOT EXISTS prompt_generation_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bank_id INT NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    generation_status VARCHAR(20) NOT NULL COMMENT 'completed, failed, partial',
    llm_provider VARCHAR(50) DEFAULT NULL COMMENT 'OpenAI, Anthropic, etc.',
    llm_model VARCHAR(100) DEFAULT NULL COMMENT 'Model name used',
    prompt_tokens INT DEFAULT NULL,
    completion_tokens INT DEFAULT NULL,
    total_tokens INT DEFAULT NULL,
    error_message TEXT DEFAULT NULL,
    generation_time_ms INT DEFAULT NULL COMMENT 'Time taken for generation',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_bank_country (bank_id, country_code),
    INDEX idx_status (generation_status),
    INDEX idx_created (created_at),
    FOREIGN KEY (bank_id) REFERENCES banks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Audit log for LLM prompt generation attempts';

-- ============================================================
-- Table 4: prompt_feedback
-- Collect feedback on prompt quality for optimization
-- ============================================================

CREATE TABLE IF NOT EXISTS prompt_feedback (
    id INT AUTO_INCREMENT PRIMARY KEY,
    prompt_id INT NOT NULL,
    extraction_quality FLOAT DEFAULT NULL COMMENT '0.0-1.0 quality score',
    correct_extractions INT DEFAULT 0,
    incorrect_extractions INT DEFAULT 0,
    false_positives INT DEFAULT 0,
    false_negatives INT DEFAULT 0,
    feedback_source VARCHAR(50) DEFAULT NULL COMMENT 'manual, auto_validation, etc.',
    document_id VARCHAR(100) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_prompt (prompt_id),
    INDEX idx_quality (extraction_quality),
    INDEX idx_created (created_at),
    FOREIGN KEY (prompt_id) REFERENCES bank_gliner_prompts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Feedback on prompt quality for optimization';

-- ============================================================
-- PERFORMANCE INDEXES
-- ============================================================

-- Composite index for prompt lookups (most common query)
CREATE INDEX IF NOT EXISTS idx_prompts_lookup_composite ON bank_gliner_prompts(bank_id, country_code, is_active, entity_type);

-- Index for finding popular/unused prompts
CREATE INDEX IF NOT EXISTS idx_prompts_usage_stats ON bank_gliner_prompts(usage_count DESC, last_used_at);

-- Index for config status queries
CREATE INDEX IF NOT EXISTS idx_config_status_active ON bank_extraction_config(prompt_generation_status, is_active);

-- ============================================================
-- VERIFICATION
-- ============================================================

-- Verify bank_gliner_prompts table structure
-- SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, COLUMN_COMMENT
-- FROM INFORMATION_SCHEMA.COLUMNS
-- WHERE TABLE_NAME = 'bank_gliner_prompts'
-- ORDER BY ORDINAL_POSITION;

-- Verify bank_extraction_config table structure
-- SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, COLUMN_COMMENT
-- FROM INFORMATION_SCHEMA.COLUMNS
-- WHERE TABLE_NAME = 'bank_extraction_config'
-- ORDER BY ORDINAL_POSITION;

-- Check if tables were created successfully
-- SELECT TABLE_NAME, TABLE_COMMENT
-- FROM INFORMATION_SCHEMA.TABLES
-- WHERE TABLE_SCHEMA = DATABASE()
--   AND TABLE_NAME IN ('bank_gliner_prompts', 'bank_extraction_config', 'prompt_generation_history', 'prompt_feedback');

-- ============================================================
-- ROLLBACK
-- ============================================================

-- To rollback this migration:
-- DROP TABLE IF EXISTS prompt_feedback;
-- DROP TABLE IF EXISTS prompt_generation_history;
-- DROP TABLE IF EXISTS bank_extraction_config;
-- DROP TABLE IF EXISTS bank_gliner_prompts;
