-- ============================================================
-- Migration 010: Add Missing Indian Banks
-- Purpose: Add all Indian banks from india.js that are missing
--          from the database (114 banks total)
-- Source: /Users/mano/Downloads/india.js
-- ============================================================

INSERT INTO banks (swift_code, country_code, legal_name, abbreviations, common_names, is_active) VALUES
-- Major Indian Banks (including previously missing IDBI, etc.)
('IBKLINBB', 'IN', 'IDBI Bank Limited', 'IDBI,IBKL', 'IDBI Bank,IDBI Bank Limited,Industrial Development Bank of India', 1),
('INDBINBB', 'IN', 'IndusInd Bank Limited', 'INDUSIND,INDB', 'IndusInd Bank,IndusInd Bank Limited', 1),
('KARBINBB', 'IN', 'Karnataka Bank Limited', 'KARNATAKA,KARB', 'Karnataka Bank,Karnataka Bank Limited', 1),
('SOININBB', 'IN', 'South Indian Bank Limited', 'SOUTH,SIB,SOIN', 'South Indian Bank,SIB,South Indian Bank Limited', 1),

-- Foreign Banks Operating in India
('ABBLINBB', 'IN', 'AB BANK LIMITED', 'ABBL', 'AB BANK LIMITED', 1),
('ABNAINBB', 'IN', 'NATWEST MARKETS PLC, INDIA BRANCH (FORMERLY KNOWN AS RBS PLC)', 'ABNA', 'NATWEST MARKETS PLC,NATWEST,RBS', 1),
('ANZBINBX', 'IN', 'AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED', 'ANZB,ANZ', 'ANZ Bank,ANZ', 1),
('BARCINAG', 'IN', 'BARCLAYS BANK PLC', 'BARC', 'Barclays,Barclays Bank', 1),
('BBKUINBB', 'IN', 'BANK OF BAHRAIN AND KUWAIT B.S.C.', 'BBKU', 'Bank of Bahrain and Kuwait', 1),
('BCEYIN5M', 'IN', 'BANK OF CEYLON', 'BCEY', 'Bank of Ceylon', 1),
('BKCHINBB', 'IN', 'BANK OF CHINA INDIA BRANCH', 'BKCH', 'Bank of China', 1),
('BNPAINBBBAN', 'IN', 'BNP PARIBAS', 'BNPA', 'BNP Paribas', 1),
('BOFAIN4XMAA', 'IN', 'BANK OF AMERICA, N.A. CHENNAI', 'BOFA', 'Bank of America,BOA', 1),
('BOTKINBX', 'IN', 'MUFG BANK, LTD.', 'BOTK', 'MUFG Bank,Bank of Tokyo-Mitsubishi', 1),
('CHASINBG', 'IN', 'JPMORGAN CHASE BANK, N.A. - IFSC BANKING UNIT (IBU) GIFT CITY BRANCH', 'CHAS', 'JP Morgan Chase,JPMorgan', 1),
('CITIINBXBLR', 'IN', 'CITIBANK N.A.', 'CITI', 'Citibank,Citi Bank', 1),
('CRESINBB', 'IN', 'CREDIT SUISSE AG', 'CRES', 'Credit Suisse', 1),
('CRLYINBBAHM', 'IN', 'CREDIT AGRICOLE CIB INDIA BRANCH', 'CRLY', 'Credit Agricole', 1),
('DOHBINBB', 'IN', 'DOHA BANK Q.S.C MUMBAI BRANCH', 'DOHB', 'Doha Bank', 1),
('EBILINBM', 'IN', 'EMIRATES NBD BANK (P.J.S.C)', 'EBIL', 'Emirates NBD', 1),
('HSBCINBBBGE', 'IN', 'THE HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED', 'HSBC', 'HSBC,Hongkong Shanghai Bank', 1),
('HVBKIN5M', 'IN', 'WOORI BANK, INDIA', 'HVBK', 'Woori Bank', 1),
('ICBKINBB', 'IN', 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA MUMBAI BRANCH', 'ICBK', 'ICBC,Industrial and Commercial Bank of China', 1),
('IBKOINDD', 'IN', 'INDUSTRIAL BANK OF KOREA, NEW DELHI BRANCH', 'IBKO', 'Industrial Bank of Korea', 1),
('MHCBINBB', 'IN', 'MIZUHO BANK, LTD.', 'MHCB', 'Mizuho Bank', 1),
('MSHQINBB', 'IN', 'MASHREQ BANK', 'MSHQ', 'Mashreq Bank', 1),
('NBADINBB', 'IN', 'FIRST ABU DHABI BANK PJSC (FORMERLY NATIONAL BANK OF ABU DHABI)', 'NBAD', 'First Abu Dhabi Bank,NBAD', 1),
('NOSCINBBBLR', 'IN', 'BANK OF NOVA SCOTIA, THE', 'NOSC', 'Scotiabank,Bank of Nova Scotia', 1),
('QNBAINBB', 'IN', 'QATAR NATIONAL BANK (Q.P.S.C.)', 'QNBA', 'Qatar National Bank,QNB', 1),
('RABOINBB', 'IN', 'COOPERATIEVE RABOBANK U.A.', 'RABO', 'Rabobank', 1),
('SABRINDD', 'IN', 'SBERBANK', 'SABR', 'Sberbank', 1),
('SCBLINBBMDS', 'IN', 'STANDARD CHARTERED BANK', 'SCBL', 'Standard Chartered,StanChart', 1),
('SHBKINBB', 'IN', 'SHINHAN BANK', 'SHBK', 'Shinhan Bank', 1),
('SMBCINDD', 'IN', 'SUMITOMO MITSUI BANKING CORPORATION NEW DELHI BRANCH', 'SMBC', 'Sumitomo Mitsui Banking Corporation', 1),
('SOGEINBBBLR', 'IN', 'SOCIETE GENERALE', 'SOGE', 'Societe Generale,SocGen', 1),
('STCBINBXNPT', 'IN', 'SBM BANK (INDIA) LIMITED', 'STCB', 'SBM Bank,State Bank of Mauritius', 1),
('UOVBINBB', 'IN', 'UNITED OVERSEAS BANK LIMITED MUMBAI BRANCH', 'UOVB', 'United Overseas Bank,UOB', 1),
('VTBRINDD', 'IN', 'JSC VTB BANK', 'VTBR', 'VTB Bank', 1),
('NACFINDD', 'IN', 'NONGHYUP BANK', 'NACF', 'Nonghyup Bank', 1),
('KOEXIN55', 'IN', 'KEB HANA BANK CHENNAI BRANCH', 'KOEX', 'KEB Hana Bank,Hana Bank', 1),
('CTCBINDD', 'IN', 'CTBC BANK CO., LTD NEW DELHI BRANCH', 'CTCB', 'CTBC Bank', 1),
('CZNBINDD', 'IN', 'KOOKMIN BANK', 'CZNB', 'Kookmin Bank', 1),

-- Indian Public Sector Banks
('CNRBINBBWXM', 'IN', 'CANARA BANK', 'CNRB', 'Canara Bank', 1),
('IDIBINBBNDM', 'IN', 'INDIAN BANK', 'IDIB', 'Indian Bank', 1),
('PSIBINBB020', 'IN', 'PUNJAB AND SIND BANK', 'PSIB', 'Punjab and Sind Bank', 1),
('ORBCINBBAGA', 'IN', 'PUNJAB NATIONAL BANK (E-OBC)', 'ORBC', 'Oriental Bank of Commerce', 1),
('UTBIINBBSGR', 'IN', 'PUNJAB NATIONAL BANK (E-UBI)', 'UTBI', 'United Bank of India', 1),
('ANDBINBBHYD', 'IN', 'UNION BANK OF INDIA, FORMERLY ANDHRA BANK', 'ANDB', 'Andhra Bank,Union Bank of India', 1),
('RBISINBB', 'IN', 'RESERVE BANK OF INDIA', 'RBIS', 'RBI,Reserve Bank', 1),
('EIBIINBB', 'IN', 'EXPORT-IMPORT BANK OF INDIA', 'EIBI', 'EXIM Bank,Export Import Bank', 1),
('SIDBINBBCBB', 'IN', 'SMALL INDUSTRIES DEVELOPMENT BANK OF INDIA', 'SIDB', 'SIDBI', 1),

-- Indian Private Sector Banks
('BNDNINCC', 'IN', 'BANDHAN BANK LIMITED', 'BNDN', 'Bandhan Bank', 1),
('DBSSINBB', 'IN', 'DBS BANK INDIA LIMITED', 'DBSS', 'DBS Bank', 1),
('DCBLINBB036', 'IN', 'DCB BANK LIMITED', 'DCBL', 'DCB Bank,Development Credit Bank', 1),
('IDFBINBI', 'IN', 'IDFC BANK LIMITED', 'IDFB', 'IDFC First Bank', 1),
('IDFIINAA', 'IN', 'IDFC FIRST BANK LIMITED - GIFT CITY', 'IDFI', 'IDFC First Bank', 1),
('EQTBIN55', 'IN', 'EQUITAS SMALL FINANCE BANK LIMITED', 'EQTB', 'Equitas Small Finance Bank', 1),
('ESFAINBB', 'IN', 'ESAF SMALL FINANCE BANK LIMITED', 'ESFA', 'ESAF Small Finance Bank', 1),
('AUBLINBB', 'IN', 'AU SMALL FINANCE BANK LIMITED', 'AUBL', 'AU Small Finance Bank', 1),
('PMCBINBBBLR', 'IN', 'UNITY SMALL FINANCE BANK LIMITED', 'PMCB', 'Unity Small Finance Bank', 1),
('CSYBIN55', 'IN', 'CSB BANK LIMITED', 'CSYB', 'CSB Bank,Catholic Syrian Bank', 1),
('TJSKINBBANE', 'IN', 'TJSB SAHAKARI BANK LTD.', 'TJSK', 'TJSB Sahakari Bank', 1),

-- Cooperative Banks
('ACBLINBB', 'IN', 'ABHYUDAYA CO-OPERATIVE BANK LTD.', 'ACBL', 'Abhyudaya Cooperative Bank', 1),
('BCMLINBB', 'IN', 'BHARAT CO-OPERATIVE BANK (MUMBAI) LTD', 'BCML', 'Bharat Cooperative Bank', 1),
('BMCBINBB', 'IN', 'BOMBAY MERCANTILE COOPERATIVE BANK LIMITED', 'BMCB', 'Bombay Mercantile Cooperative Bank', 1),
('BSSEINBB', 'IN', 'BASSEIN CATHOLIC CO-OPERATIVE BANK LIMITED', 'BSSE', 'Bassein Catholic Cooperative Bank', 1),
('COSDINBB', 'IN', 'THE COSMOS CO-OPERATIVE BANK LTD.', 'COSD', 'Cosmos Cooperative Bank', 1),
('KALUINAA', 'IN', 'THE KALUPUR COMMERCIAL CO-OPERATIVE BANK LIMITED', 'KALU', 'Kalupur Commercial Cooperative Bank', 1),
('MSCIINBB', 'IN', 'MAHARASHTRA STATE CO-OPERATIVE BANK LTD., THE', 'MSCI', 'Maharashtra State Cooperative Bank', 1),
('NKGSINBB', 'IN', 'NKGSB CO OP BANK LTD', 'NKGS', 'NKGSB Cooperative Bank', 1),
('SRCBINBBGHT', 'IN', 'THE SARASWAT CO-OPERATIVE BANK LTD.', 'SRCB', 'Saraswat Cooperative Bank', 1),

-- Financial Institutions & Clearing Corporations
('CCILINBB', 'IN', 'CLEARING CORPORATION OF INDIA LTD, THE', 'CCIL', 'Clearing Corporation of India', 1),
('CDIFINB2', 'IN', 'CDSL IFSC LIMITED', 'CDIF', 'CDSL IFSC', 1),
('IICCINBB', 'IN', 'INDIA INTERNATIONAL CLEARING CORPORATION(IFSC LIMITED', 'IICC', 'India International Clearing Corporation', 1),
('NICCINBB', 'IN', 'NSE IFSC CLEARING CORPORATION LIMITED', 'NICC', 'NSE IFSC Clearing', 1),
('SDOMINBI', 'IN', 'SWIFT INDIA DOMESTIC SERVICES PR. LTD', 'SDOM', 'SWIFT India', 1),
('SWHTIN4K', 'IN', 'SWIFT S.C.R.L', 'SWHT', 'SWIFT SCRL', 1),

-- Financial Services Companies (Securities, Brokers, etc.)
('ASTKINC2', 'IN', 'ASHIKA STOCK BROKING LIMITED', 'ASTK', 'Ashika Stock Broking', 1),
('DHSEINB2', 'IN', 'DHARAMSHI SECURITIES PVT LTD', 'DHSE', 'Dharamshi Securities', 1),
('EAIEINB2', 'IN', 'EAST INDIA SECURITIES LTD', 'EAIE', 'East India Securities', 1),
('ECSLINBB', 'IN', 'NUVAMA CUSTODIAL SERVICES LIMITED', 'ECSL', 'Nuvama Custodial Services', 1),
('EESCINBB', 'IN', 'CES LIMITED.', 'EESC', 'CES Limited', 1),
('GAIIINDD', 'IN', 'GAIL (INDIA) LIMITED', 'GAII', 'GAIL India', 1),
('GOLDINBB', 'IN', 'GOLDMAN SACHS (INDIA) CAPITAL MARKETS PRIVATE LIMITED', 'GOLD', 'Goldman Sachs', 1),
('GOTPINB2', 'IN', 'BRISKPE', 'GOTP', 'Briskpe', 1),
('GRSVINB2', 'IN', 'GRISHMA SECURITIES PRIVATE LIMITED', 'GRSV', 'Grishma Securities', 1),
('ICWPINB2', 'IN', 'INCRED CAPITAL WEALTH PORTFOLIO MANAGERS PRIVATE LIMITED', 'ICWP', 'Incred Capital Wealth', 1),
('IDIPINB2', 'IN', 'NJ INDIA INVEST PRIVATE LIMITED', 'IDIP', 'NJ India Invest', 1),
('IDSUINB2', 'IN', 'INDIANIVESH SECURITIES LIMITED', 'IDSU', 'Indiainivesh Securities', 1),
('INHCINB2', 'IN', 'INDIANIVESH SHARES SECURITIES PRIVATE LIMITED', 'INHC', 'Indiainivesh Shares', 1),
('ISPDINBB', 'IN', 'ICICI SECURITIES PRIMARY DEALERSHIP LIMITED', 'ISPD', 'ICICI Securities', 1),
('ITLDINB2', 'IN', 'INFOSYS LIMITED', 'ITLD', 'Infosys', 1),
('KAEPINB2', 'IN', 'KAVIRAJ SECURITIES PRIVATE LIMITED', 'KAEP', 'Kaviraj Securities', 1),
('KFPRINB2', 'IN', 'KANJALOCHANA FINSERVE PRIVATE LIMITED', 'KFPR', 'Kanjalochana Finserv', 1),
('KTCPINA2', 'IN', 'KIFS TRADE CAPITAL PRIVATE LIMITED', 'KTCP', 'KIFS Trade Capital', 1),
('MSFCIN52', 'IN', 'MSE FINANCIAL SERVICES LTD', 'MSFC', 'MSE Financial Services', 1),
('MSGFINAA', 'IN', 'MORGAN STANLEY FUND ADVISOR IFSC PRIVATE LIMITED', 'MSGF', 'Morgan Stanley Fund Advisor', 1),
('MSGIINAA', 'IN', 'MORGAN STANLEY IFSC FUND', 'MSGI', 'Morgan Stanley IFSC Fund', 1),
('MSMBINBX', 'IN', 'MORGAN STANLEY INDIA COMPANY PVT LTD', 'MSMB', 'Morgan Stanley India', 1),
('MSPDINB4', 'IN', 'MORGAN STANLEY INDIA PRIMARY DEALER PRIVATE LIMITED', 'MSPD', 'Morgan Stanley Primary Dealer', 1),
('NFIEINBB', 'IN', 'NOMURA FIXED INCOME SECURITIES PRIVATE LIMITED', 'NFIE', 'Nomura Fixed Income Securities', 1),
('NSPVINB2', 'IN', 'NIRMAL BANG SECURITIES PVT LTD', 'NSPV', 'Nirmal Bang Securities', 1),
('OFCLINBB', 'IN', 'ORBIS FINANCIAL CORPORATION LTD', 'OFCL', 'Orbis Financial', 1),
('REILINBI', 'IN', 'RELIANCE INDUSTRIES LIMITED', 'REIL', 'Reliance Industries', 1),
('REVOINB2', 'IN', 'ARVOG FOREX PRIVATE LIMITED', 'REVO', 'Arvog Forex', 1),
('SAIDINB2', 'IN', 'SANFORD C. BERNSTEIN (INDIA) PRIVATE LIMITED', 'SAID', 'Sanford Bernstein', 1),
('SBSGINBB', 'IN', 'SBI-SG GLOBAL SECURITIES SERVICES PVT LTD', 'SBSG', 'SBI-SG Global Securities', 1),
('SGSEINB2', 'IN', 'SOCIETE GENERALE SECURITIES INDIA PRIVATE LIMITED', 'SGSE', 'Societe Generale Securities', 1),
('SHCIINBI', 'IN', 'STOCK HOLDING CORPORATION OF INDIA LIMITED', 'SHCI', 'Stock Holding Corporation of India,SHCIL', 1),
('SKYDINB2', 'IN', 'SKYDO TECHNOLOGIES PRIVATE LIMITED', 'SKYD', 'Skydo Technologies', 1),
('TASYINBI', 'IN', 'TATA SKY LTD', 'TASY', 'Tata Sky', 1),
('TCILINBB', 'IN', 'THOMAS COOK (INDIA) LTD.', 'TCIL', 'Thomas Cook India', 1),
('TPRSINB2', 'IN', 'TRANSPURE SOLUTIONS PRIVATE LIMITED', 'TPRS', 'Transpure Solutions', 1),
('TRBIINBB', 'IN', 'TRANSUNION CIBIL LIMITED', 'TRBI', 'TransUnion CIBIL', 1),
('TSTEINBI', 'IN', 'TATA STEEL LIMITED', 'TSTE', 'Tata Steel', 1),
('XBOMINBB', 'IN', 'BOMBAY STOCK EXCHANGE LIMITED', 'XBOM', 'BSE,Bombay Stock Exchange', 1),
('BSONINCC', 'IN', 'SONALI BANK', 'BSON', 'Sonali Bank', 1),
('IBBKINBB', 'IN', 'PT BANK MAYBANK INDONESIA TBK', 'IBBK', 'Maybank Indonesia', 1)

ON DUPLICATE KEY UPDATE
    legal_name = VALUES(legal_name),
    abbreviations = VALUES(abbreviations),
    common_names = VALUES(common_names),
    is_active = VALUES(is_active);
